stages:
  - build
  - style
  - test
  - deploy

build-code-job:
  stage: build
  tags:
    - build
  script:
    - cd src/cat/
    - make s21_cat
    - cd ../grep/
    - make s21_grep
  artifacts:
    paths:
      - src/cat/
      - src/grep/
    expire_in: 30 days
  after_script:
      - sh src/notify.sh "build"

codestyle:
  stage: style
  tags: 
    - style
  script:
    - cp -r materials/linters/.clang-format src/cat/
    - cd src/cat/
    - make style
    - mv .clang-format ../grep/
    - cd ../grep/
    - make style
  after_script:
      - sh src/notify.sh "style"
 
test_code:
  stage: test
  tags:
    - test
  script:
    - cd src/cat
    - make test 
    - cd ../grep/tests
    - bash run_tests.sh
  when: on_success
  after_script:
      - sh src/notify.sh "test"
 
deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - expect src/copy.sh
  when: manual
  after_script:
      - sh src/notify.sh "deploy" 
